[DO NOT MERGE] PP-11682 Replace 'request' package with 'axios' for 'cardid.client'.
alphagov/pay-frontend pull request #3823
Opened 2024-04-15 18:10 UTC by JFSGDS

https://payments-platform.atlassian.net/browse/PP-11682

## WHAT
- Add axios-base-client from latest pay-js-commons.
- Import config files.
- Remove ‘base.client’ reference.

## HOW 

- All automated tests should pass preferably without the need to be amended.
- Existing functionality should remain unaffected.

2024-04-16 11:59 UTC, iqbalgds commented on app/models/card.js
> +        // const body = response.body
Just need to remove this

2024-04-16 12:00 UTC, iqbalgds requested changes
1 very minor comment

2024-04-16 12:07 UTC, iqbalgds requested changes
Just a minor thing.

2024-04-16 12:07 UTC, iqbalgds commented on app/services/clients/cardid.client.js
> +  try {
We don't need a try / catch here.

The calling method wraps this in a promise anyway and will deal with the error.

2024-04-16 12:18 UTC, JFSGDS commented on app/models/card.js
> +        // const body = response.body
Good spot. Done.

2024-04-17 08:43 UTC, iqbalgds commented on app/services/clients/cardid.client.js
> +  try {
As discussed, this is no longer required.
As Axios behaves a bit differently to request library.

2024-04-17 08:46 UTC, merged